services:
  postgres:
    image: postgis/postgis:16-3.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: madmaps
      POSTGRES_PASSWORD: madmaps
      POSTGRES_DB: madmaps
    ports:
      - "5433:5432"
    volumes:
      - mapinski_postgres_data:/var/lib/postgresql/data

volumes:
  mapinski_postgres_data:
